server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: package-service-packages
            uri: lb://package-service
            predicates:
              - Path=/api/touristpackages/**
          - id: package-service-discounts
            uri: lb://package-service
            predicates:
              - Path=/api/discounts/**
          - id: package-service-promotions
            uri: lb://package-service
            predicates:
              - Path=/api/promotions/**
          - id: search-service
            uri: lb://search-service
            predicates:
              - Path=/api/search/**
          - id: reservation-service
            uri: lb://reservation-service
            predicates:
              - Path=/api/reservations/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/payments/**
          - id: tracking-service
            uri: lb://tracking-service
            predicates:
              - Path=/api/tracking/**
          - id: report-service
            uri: lb://report-service
            predicates:
              - Path=/api/reports/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
