server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:postgresql://${DB_RESERVATION_HOST:localhost}:5432/${DB_RESERVATION_NAME:db_reservations}
    username: ${DB_RESERVATION_USER:postgres}
    password: ${DB_RESERVATION_PASS:sarumi}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
