# ============================================================
# PostgreSQL para payment-service
# ============================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres
spec:
  selector:
    matchLabels:
      app: payment-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: dbname
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: payment-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres
spec:
  selector:
    app: payment-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
