# ============================================================
# Reservation Service — M4, puerto dinámico, ClusterIP
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  selector:
    matchLabels:
      app: reservation-service
  replicas: 1
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: sarumimope/reservation-service:latest
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-service:8888"
            - name: EUREKA_URL
              value: "http://eureka-service:8761/eureka"
            - name: DB_RESERVATION_HOST
              value: "reservation-postgres"
            - name: DB_RESERVATION_NAME
              valueFrom:
                secretKeyRef:
                  name: reservation-db-secret
                  key: dbname
            - name: DB_RESERVATION_USER
              valueFrom:
                secretKeyRef:
                  name: reservation-db-secret
                  key: username
            - name: DB_RESERVATION_PASS
              valueFrom:
                secretKeyRef:
                  name: reservation-db-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  selector:
    app: reservation-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
