# ============================================================
# Search Service — M3, puerto dinámico, ClusterIP
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  selector:
    matchLabels:
      app: search-service
  replicas: 1
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: sarumimope/search-service:latest
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-service:8888"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-service:8888"
            - name: EUREKA_URL
              value: "http://eureka-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
